name: Fetch Apple & CDN IPs

on:
  schedule:
    - cron: "0 0 * * 1"  # 每周一 00:00 UTC 执行
  workflow_dispatch:     # 也允许手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Fetch IP ranges
        run: |
          python scripts/fetch_asn.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.txt
          git commit -m "Update IP ranges [auto]" || echo "No changes to commit"
          git push
