name: get-apple_china-list

# 定义触发器，定期执行此工作流
on:
  schedule:
    - cron: '0 0 */15 * *'  # 每天午夜运行一次
  workflow_dispatch:  # 手动触发

permissions:
  contents: write  # 允许 GitHub Actions 推送代码
  issues: write    # 允许 GitHub Actions 管理 issues

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # 检出代码仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 拉取远程文件
    - name: Download conf file
      run: |
        curl -o ip-cidr.txt https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
        curl -o apple_cidr4.collection https://raw.githubusercontent.com/Teacher-c/clash/refs/heads/main/apple_cidr4_collection.txt
        curl -o china_ip6_route.txt https://ispip.clang.cn/all_cn_ipv6.txt
        curl -o apple_cidr6.collection https://raw.githubusercontent.com/Teacher-c/clash/refs/heads/main/apple_cidr6_collection.txt
        
    # 使用 sed 命令修改文件
    - name: Modify file
      run: |
        sed -i '/^\s*$/d; /^#/d' *.conf *.txt *.collection
        #提取ip
        rm -rf CN-ip-cidr.txt
        cat apple_cidr4.collection ip-cidr.txt >> CN-ip-cidr.txt
        
        rm -rf CN-ip-cidr6.txt
        cat apple_cidr6.collection china_ip6_route.txt >> CN-ip-cidr6.txt

        rm -rf ip-cidr.txt apple_cidr4.collection china_ip6_route.txt apple_cidr6.collection
        

    # 提交修改并推送到仓库
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update file"
        git push
