name: get-apple_china-list

# 定义触发器，定期执行此工作流
on:
  schedule:
    - cron: '0 0 */15 * *'  # 每天午夜运行一次
  workflow_dispatch:  # 手动触发

permissions:
  contents: write  # 允许 GitHub Actions 推送代码
  issues: write    # 允许 GitHub Actions 管理 issues

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # 检出代码仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 拉取远程文件
    - name: Download conf file
      run: |
        curl -o apple_cn.conf https://ruleset.skk.moe/List/non_ip/apple_cn.conf
        curl -o apple_cdn.conf https://ruleset.skk.moe/List/non_ip/apple_cdn.conf
        curl -o microsoft_cdn.conf https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf
    # 使用 sed 命令修改文件
    - name: Modify file
      run: |
        sed -i '/^\s*$/d; /^[#]/d; /^IP-CIDR/d; s/DOMAIN,/server=\//g; s/DOMAIN-SUFFIX,/server=\//g; s/$/\/114.114.114.114/' apple_cn.conf
        sed -i '/^\s*$/d; /^[#]/d; /^IP-CIDR/d; s/DOMAIN,/server=\//g; s/DOMAIN-SUFFIX,/server=\//g; s/$/\/114.114.114.114/' apple_cdn.conf
        sed -i '/^\s*$/d; /^[#]/d; /^IP-CIDR/d; s/DOMAIN,/server=\//g; s/DOMAIN-SUFFIX,/server=\//g; s/$/\/114.114.114.114/' microsoft_cdn.conf

    # 提交修改并推送到仓库
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add apple_cn.conf
        git add apple_cdn.conf
        git add microsoft_cdn.conf
        git commit -m "Update file"
        git push
